// Code generated by mockery v2.26.1. DO NOT EDIT.

package servicediscovery

import mock "github.com/stretchr/testify/mock"

// MockDiscoveryErrCallback is an autogenerated mock type for the DiscoveryErrCallback type
type MockDiscoveryErrCallback struct {
	mock.Mock
}

type MockDiscoveryErrCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiscoveryErrCallback) EXPECT() *MockDiscoveryErrCallback_Expecter {
	return &MockDiscoveryErrCallback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: err
func (_m *MockDiscoveryErrCallback) Execute(err error) {
	_m.Called(err)
}

// MockDiscoveryErrCallback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDiscoveryErrCallback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - err error
func (_e *MockDiscoveryErrCallback_Expecter) Execute(err interface{}) *MockDiscoveryErrCallback_Execute_Call {
	return &MockDiscoveryErrCallback_Execute_Call{Call: _e.mock.On("Execute", err)}
}

func (_c *MockDiscoveryErrCallback_Execute_Call) Run(run func(err error)) *MockDiscoveryErrCallback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockDiscoveryErrCallback_Execute_Call) Return() *MockDiscoveryErrCallback_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDiscoveryErrCallback_Execute_Call) RunAndReturn(run func(error)) *MockDiscoveryErrCallback_Execute_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockDiscoveryErrCallback interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDiscoveryErrCallback creates a new instance of MockDiscoveryErrCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDiscoveryErrCallback(t mockConstructorTestingTNewMockDiscoveryErrCallback) *MockDiscoveryErrCallback {
	mock := &MockDiscoveryErrCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
