// Code generated by mockery v2.26.1. DO NOT EDIT.

package servicediscovery

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceProvider is an autogenerated mock type for the ServiceProvider type
type MockServiceProvider struct {
	mock.Mock
}

type MockServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceProvider) EXPECT() *MockServiceProvider_Expecter {
	return &MockServiceProvider_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx
func (_m *MockServiceProvider) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockServiceProvider_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceProvider_Expecter) Run(ctx interface{}) *MockServiceProvider_Run_Call {
	return &MockServiceProvider_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockServiceProvider_Run_Call) Run(run func(ctx context.Context)) *MockServiceProvider_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceProvider_Run_Call) Return(_a0 error) *MockServiceProvider_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_Run_Call) RunAndReturn(run func(context.Context) error) *MockServiceProvider_Run_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockServiceProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockServiceProvider creates a new instance of MockServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockServiceProvider(t mockConstructorTestingTNewMockServiceProvider) *MockServiceProvider {
	mock := &MockServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
